### ISSUE TITLE
Support ARM / multi-architecture

### ISSUE THREAD

**Issue by joeloplot** [palfrey/wait-for-db#63]
wait-for-db is unfortunately x86 specific but making it multi architecture shouldn't be too difficult. Happy to contribute, I'm just logging it as an issue to discuss. 

The easy bit is just adding
```
ARG ARCH=
FROM ${ARCH}alpine:blah
```
to the Dockerfile and using buildx. The harder part is selecting the appropriate musl (etc) for whatever `$ARCH` is being built, I think. Both very doable.

**Comment by palfrey** [comment]
I don't have an ARM machine I need this for myself, but I'm happy to see PRs for this, provided at least ARM is tested in CI as well as x86.

**Comment by palfrey** [comment]
https://github.com/palfrey/wait-for-db/pull/68 enables multiarch builds. Need to do a new release with this setup now...

**Comment by palfrey** [comment]
See https://github.com/palfrey/wait-for-db/releases/tag/v1.4.0
