### ISSUE TITLE
Provide a pre-built Docker image

### ISSUE THREAD

**Issue by joeloplot** [palfrey/wait-for-db#64]
Is the Dockerfile being built and pushed anywhere please?

**Comment by palfrey** [comment]
No. What's your use case for it? Would have thought most usages want to be inside a Docker image i.e. download the static binary.

**Comment by joeloplot** [comment]
I would use it as an initContainer for a kubernetes Pod. That means Kubernetes would take care of ensuring that it completes, before starting the main container(s) in the pod. 

Of course, I can build my own image, but it's actually much better to have a standalone one than to have it in my app container, so having a prebuilt image (essentially just pushing to docker hub / quay.io / ... at the end of your workflow file) would be fantastic. 

Hope that makes sense! Happy to help with a PR.

**Comment by palfrey** [comment]
Easiest way was just to use quay.io's builders. See https://quay.io/repository/palfrey/wait-for-db?tab=tags
